Создание таблиц с данными о странах
travelly-life/dictionary-service pull request #1
Opened 2023-07-13 06:45 UTC by skrooodg

2023-07-13 07:30 UTC, blackMaster007 requested changes
не пройден тест

2023-07-13 07:35 UTC, blackMaster007 requested changes

2023-07-13 07:35 UTC, blackMaster007 commented on src/main/java/entity/city.java
> +    private BigInteger id;
должен быть тип, соответствующий bigserial (по поиску на странице найдешь в этой статье)
https://javarush.com/groups/posts/2579-dobavljaem-bd-k-restful-servisu-na-spring-boot-chastjh-1

2023-07-13 07:35 UTC, blackMaster007 commented on src/main/resources/db/changelog/v1-0/createTableCity.xml
> +            <column name="id" type="BIGINT" autoIncrement="true">
тип должен быть Bigserial

2023-07-13 09:43 UTC, skrooodg commented on src/main/java/entity/city.java
> +    private BigInteger id;
исправлкео

2023-07-13 09:43 UTC, skrooodg commented on src/main/resources/db/changelog/v1-0/createTableCity.xml
> +            <column name="id" type="BIGINT" autoIncrement="true">
исправлено

2023-07-13 17:39 UTC, travelly-life commented on src/main/java/entity/city.java
> +public class city {
название класса с большой буквы

2023-07-13 17:39 UTC, travelly-life commented on src/main/java/entity/city.java
> +package entity;
исправить расположение папки entity 
переместить в package com.travelly.dictionaryservice

2023-07-13 17:39 UTC, travelly-life commented on src/main/java/entity/city.java
> +    private BigInteger region_id;
заменить на тип Long

2023-07-13 17:39 UTC, travelly-life commented on src/main/java/entity/country.java
> +public class country {
название класса с большой буквы

2023-07-13 17:39 UTC, travelly-life commented on src/main/java/entity/country.java
> +    private BigInteger id;
тип Long

2023-07-13 17:39 UTC, travelly-life commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:62015/mydatabase
исправить название датасорса jdbc:postgresql://localhost:5432/dictionary-service

2023-07-13 17:39 UTC, travelly-life commented on src/main/resources/application.yml
> +    password: secret
username: postgres
    password: admin

2023-07-13 17:39 UTC, travelly-life commented on src/main/resources/application.yml
> +    password: secret
изменить по аналогии с datasource

2023-07-13 20:32 UTC, skrooodg commented on src/main/java/entity/city.java
> +public class city {
Исправил

2023-07-13 20:32 UTC, skrooodg commented on src/main/java/entity/city.java
> +package entity;
исправил

2023-07-13 20:33 UTC, skrooodg commented on src/main/java/entity/city.java
> +    private BigInteger region_id;
исправил

2023-07-14 13:15 UTC, skrooodg commented on src/main/resources/application.yml
> +    password: secret
исправил

2023-07-14 13:16 UTC, skrooodg commented on src/main/resources/application.yml
> +    password: secret
исправил (хотя такие данные стояли тут по умолчанию, поэтому их и не менял=)

2023-07-14 13:17 UTC, skrooodg commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:62015/mydatabase
исправил на jdbc:postgresql://localhost:5432/postgres
сделать датасорс таким, как ты просишь  не могу. Потратил на это день но так и не понял почему не создает такую БД. Пишет что ее не существует. ПАМАГИ пожалуйста если это сильно критично
Менял файл compose и в докере контейнер сносил и делал новый, но все равно ничего не получается

2023-07-14 15:31 UTC, merged